alias ghf="cd ~/Documents/GitHub/"
alias ghghf="cd ~/github/github/"
alias bonesf="cd ~/Documents/GitHub/Bones/"
alias jcbf="code ~/Documents/GitHub/jchuerva.github.io/"
alias jks="bundle exec jekyll serve"
alias lint="bundle exec rubocop && yarn lint"
alias rbc="rubocop"
alias frbc="rubocop -A"
alias flint="bundle exec rubocop -a"
alias rollback="rake db:rollback STEP=1"